feat: add upstash redis driver
unjs/unstorage pull request #289
Opened 2023-08-17 12:58 UTC by Hebilicious

- feat: add redis-upstash
- feat: implement upstash redis driver
- docs: add upstash docs

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-10-01 09:14 UTC, chronark commented
Hey there!
(disclaimer: I work for upstash)

quick question: why did you install `@vercel/kv` and then use `@upstash/redis`
It seems to work cause their package is just a wrapper around `@upstash/redis` but it seemed weird :D

secondly: we can provde a db for unit tests for free, just let me know :)

2023-10-02 07:56 UTC, Hebilicious commented
> Hey there! (disclaimer: I work for upstash)
> 
> quick question: why did you install `@vercel/kv` and then use `@upstash/redis` It seems to work cause their package is just a wrapper around `@upstash/redis` but it seemed weird :D
> 
> secondly: we can provde a db for unit tests for free, just let me know :)

Hello there! @vercel/kv is already a driver supported by unstorage, this PR doesn't install it. I didn't know their package was just a wrapper.

On providing us with a DB, I think that would be great ! 
@pi0 is the maintainer of unstorage, so he'll need to green light this

2023-10-09 09:41 UTC, Atinux commented
Do you mind resolving the conflicts @Hebilicious ?

2023-10-09 10:34 UTC, Hebilicious commented
> Do you mind resolving the conflicts @Hebilicious ?

Sure. For full context, when vercel-kv was added in https://github.com/unjs/unstorage/pull/213, @redis/upstash was added as a dependency because it is a vercel-kv dependency, so that makes it easier for pnpm users. 

This PR adds a redis-upstash driver for the use case where you want to use upstash without vercel (which I encountered recently)

I'll add this to the PR description.

2023-10-09 10:59 UTC, pi0 requested changes

2023-10-09 10:59 UTC, pi0 commented on .env.example
> +UPSTASH_REDIS_REST_TOKEN=""
please remove these / any local testing bits

2023-10-09 10:59 UTC, pi0 commented on docs/content/6.drivers/redis.md
> +## Upstash Redis
This section shall be in `upstash.md`

2023-10-09 10:59 UTC, pi0 commented on package.json
> +    "dotenv": "^16.3.1",
remove this

2023-10-09 10:59 UTC, pi0 commented on src/drivers/redis-upstash.ts
We can simplify driver name to upstash with an alias to upstash-redis as this is only upstash/kv storage option now.

2023-10-09 10:59 UTC, pi0 commented on src/drivers/redis-upstash.ts
> +export interface RedisOptions extends Partial<RedisConfigNodejs> {
Interface should be `UpstashRedisOptions`

2023-10-09 10:59 UTC, pi0 commented on src/types.ts
> +    opts?: TransactionOptions
This is out of scope of this PR

2023-10-09 11:04 UTC, pi0 commented
Hi dear @chronark thanks for reaching out and for your offer about the CI plan.

I would ideally love to have a proper "unit" test for both drivers. I think we can mock the HTTP client with upstash API. If you have a tool or package that can help in this regard it would be awesome! Also, feel free to reach me via discord (pi0) if you would like to work closer on upstash integrations I can invite you to the unjs discord channel.

---

Off topic: Regarding vercel-kv, the main reason for having a wrapper is that it allows having "zero configuration" integration with their platform / provided environment variables - also any changes needed in the future. If there are other hosting options that provided upstash integration, we probably have to either use their packages or make a wrapper driver.

2023-10-09 11:35 UTC, pi0 commented
Thanks for the updates @Hebilicious ❤️

2023-10-11 09:05 UTC, chronark commented
@pi0 we don't have any true unit test library or similar, I'm running all of our tests against a real upstash db or in a docker container :/

I'm leaving upstash soon, joining your discord now probably won't help much unfortunately.

if you want credits for testing against real dbs, just let us know here: support@upstash.com and ideally reference this comment :D

2024-12-10 22:33 UTC, pi0 commented
Landed via https://github.com/unjs/unstorage/pull/500

2024-12-10 22:33 UTC, closed without merging